<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Barang_masuk_model extends CI_Model
{

    public $table = 'barang_masuk';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }


      // membuat kode barang otomatis
      function kode()
      {
               $this->db->select('RIGHT(barang_masuk.id_barang_masuk,2) as id_barang_masuk', FALSE);
               $this->db->order_by('id_barang_masuk','DESC');    
               $this->db->limit(1);    
               $query = $this->db->get('barang_masuk');  //cek dulu apakah ada sudah ada kode di tabel.    
               if($query->num_rows() <> 0){      
                    //cek kode jika telah tersedia    
                    $data = $query->row();      
                    $kode = intval($data->id_barang_masuk) + 1; 
               }
               else{      
                    $kode = 1;  //cek jika kode belum terdapat pada table
               }
                   $tgl=date('dmY'); 
                   $batas = str_pad($kode, 3, "0", STR_PAD_LEFT);    
                   $kodetampil = "PNR-".$tgl."-".$batas;  //format kode
                   return $kodetampil;  
     }



      // hapus temp
    function hapus_temp($id)
    {
        $this->db->where('id',$id);
        $this->db->delete('detail_barang_masuk');
    }

    // simpan ke database
    function insert_temp()
    {

         $id_barang_masuk       = $_GET['id_barang_masuk'];
         $kode_barang           = $_GET['kode_barang'];
         $nama_barang           = $_GET['nama_barang'];
         $jumlah                = $_GET['jumlah'];
         $tanggal               = $_GET['tanggal'];
      
        $data=array(
            'id_barang_masuk'=>$id_barang_masuk,
            'kode_barang'=>$kode_barang,
            'nama_barang'=>$nama_barang,
            'jumlah'=>$jumlah,
            'tanggal'=>$tanggal,
            );
        $this->db->insert('detail_barang_masuk',$data);
    }
    // simpan ke database
    function checkout2()
    {

         $id_barang_masuk   = $_GET['id_barang_masuk'];    
         $tanggal           = $_GET['tanggal'];      

        $data=array(
            'id_barang_masuk'=>$id_barang_masuk,
            'tanggal'=>$tanggal,
            );
        $this->db->insert('barang_masuk',$data);
    }


    // ambil data view dari database
    function tabel_transaksi($id)
    {
        $query="SELECT * FROM detail_barang_masuk where id_barang_masuk ='$id'";
        return $this->db->query($query);
    }


    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where('id_barang_masuk', $id);
        return $this->db->get($this->table)->row();
    }
    
    function get_by_id2($id)
    {
       $query="select a.id_barang_masuk,a.tanggal,b.kode_barang,a.nama_barang,b.jumlah from detail_barang_masuk b join barang_masuk a on a.id_barang_masuk=b.id_barang_masuk where a.id_barang_masuk='$id'";
       return $this->db->query($query)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_barang_masuk', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_barang_masuk', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Barang_masuk_model.php */
/* Location: ./application/models/Barang_masuk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-11-13 12:59:30 */
/* http://harviacode.com */