<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ongkir_model extends CI_Model
{

    public $table = 'ongkir';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }


    // membuat kode barang otomatis
    function kode()
    {
             $this->db->select('RIGHT(ongkir.kode_ongkir,2) as kode_ongkir', FALSE);
             $this->db->order_by('kode_ongkir','DESC');    
             $this->db->limit(1);    
             $query = $this->db->get('ongkir');  //cek dulu apakah ada sudah ada kode di tabel.    
             if($query->num_rows() <> 0){      
                  //cek kode jika telah tersedia    
                  $data = $query->row();      
                  $kode = intval($data->kode_ongkir) + 1; 
             }
             else{      
                  $kode = 1;  //cek jika kode belum terdapat pada table
             }
                 $tgl=date('dmY'); 
                 $batas = str_pad($kode, 3, "0", STR_PAD_LEFT);    
                 $kodetampil = "ONK".$tgl.$batas;  //format kode
                 return $kodetampil;  
   }

   function get_provinsi() {
    return $this->db->get('provinsi')->result(); // Tampilkan semua data yang ada di tabel provinsi
}

   function get_list_kab($kode_provinsi){
    $this->db->where('kode_provinsi', $kode_provinsi);
    $result = $this->db->get("kabupaten")->result(); 
    return $result; 
}



    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('kode_ongkir', $q);
	$this->db->or_like('ekspedisi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('kode_ongkir', $q);
	$this->db->or_like('ekspedisi', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Ongkir_model.php */
/* Location: ./application/models/Ongkir_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-04-20 16:38:06 */
/* http://harviacode.com */