<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sales_order_model extends CI_Model
{

    public $table = 'sales_order';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_prospek', $q);
	$this->db->or_like('id_customer', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('no_ktp', $q);
	$this->db->or_like('no_hp', $q);
	$this->db->or_like('kode_barang', $q);
	$this->db->or_like('nama_barang', $q);
	$this->db->or_like('jumlah', $q);
	$this->db->or_like('jenis_pembelian', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('tenor', $q);
	$this->db->or_like('angsuran', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('nik_sales', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->where('status','paid');
        return $this->db->get($this->table)->result();
    }
    // get data with limit and search
    function get_limit_data2($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->where('status','confirm');
        return $this->db->get($this->table)->result();
    }

    function get_by($id)
    {
        $this->db->where('id',$id);
        return $this->db->get('sales_order')->row();
    }
    function get_by2($id)
    {
        $this->db->where('id',$id);
        return $this->db->get('pembayaran')->row();
    }
    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Sales_order_model.php */
/* Location: ./application/models/Sales_order_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-11-14 13:01:27 */
/* http://harviacode.com */