<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Skema_kredit_model extends CI_Model
{

    public $table = 'skema_kredit';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }


      // membuat kode barang otomatis
      function kode()
      {
               $this->db->select('RIGHT(skema_kredit.id_skema,2) as id_skema', FALSE);
               $this->db->order_by('id_skema','DESC');    
               $this->db->limit(1);    
               $query = $this->db->get('skema_kredit');  //cek dulu apakah ada sudah ada kode di tabel.    
               if($query->num_rows() <> 0){      
                    //cek kode jika telah tersedia    
                    $data = $query->row();      
                    $kode = intval($data->id_skema) + 1; 
               }
               else{      
                    $kode = 1;  //cek jika kode belum terdapat pada table
               }
                   $tgl=date('dmY'); 
                   $batas = str_pad($kode, 3, "0", STR_PAD_LEFT);    
                   $kodetampil = "SKM".$tgl.$batas;  //format kode
                   return $kodetampil;  
     }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    

    // hapus temp
    function hapus_temp($id)
    {
        $this->db->where('id',$id);
        $this->db->delete('detail_skema');
    }

    // simpan ke database
    function insert_temp()
    {

         $id_skema              = $_GET['id_skema'];
         $kode_barang           = $_GET['kode_barang'];
         $harga                 = $_GET['harga'];
         $tenor                 = $_GET['tenor'];
         $angsuran              = $_GET['angsuran'];
         $komisi                = $_GET['komisi'];
         $kontes                = $_GET['kontes'];
         $jenis_pembelian       = $_GET['jenis_pembelian'];
      

        $data=array(
            'id_skema'=>$id_skema,
            'kode_barang'=>$kode_barang,
            'harga'=>$harga,
            'tenor'=>$tenor,
            'angsuran'=>$angsuran,
            'komisi'=>$komisi,
            'kontes'=>$kontes,
            'jenis_pembelian'=>$jenis_pembelian,
            );
        $this->db->insert('detail_skema',$data);
    }
    // simpan ke database
    function checkout2()
    {

         $id_skema              = $_GET['id_skema'];
         $kode_barang           = $_GET['kode_barang'];      

        $data=array(
            'id_skema'=>$id_skema,
            'kode_barang'=>$kode_barang,
            );
        $this->db->insert('skema_kredit',$data);
    }


    // ambil data view dari database
    function tabel_transaksi($id)
    {
        $query="SELECT * FROM detail_skema where id_skema ='$id'";
        return $this->db->query($query);
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_skema', $q);
	$this->db->or_like('kode_barang', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_skema', $q);
	$this->db->or_like('kode_barang', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Skema_kredit_model.php */
/* Location: ./application/models/Skema_kredit_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-11-10 06:41:50 */
/* http://harviacode.com */