<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tagihan_konsumen_model extends CI_Model
{

    public $table = 'tagihan_konsumen';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_prospek', $q);
	$this->db->or_like('id_customer', $q);
	$this->db->or_like('nama_konsumen', $q);
	$this->db->or_like('nominal', $q);
	$this->db->or_like('tanggal_pembayaran', $q);
	$this->db->or_like('keterangan', $q);
    $this->db->or_like('status', $q);
    $this->db->from($this->table);
    $this->db->group_by('id_prospek');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_prospek', $q);
	$this->db->or_like('id_customer', $q);
	$this->db->or_like('nama_konsumen', $q);
	$this->db->or_like('nominal', $q);
	$this->db->or_like('tanggal_pembayaran', $q);
	$this->db->or_like('keterangan', $q);
    $this->db->or_like('status', $q);
    $this->db->group_by('id_prospek');
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
    function total_rows2($q = NULL,$id_prospek) {
        $this->db->like('id', $q);
	$this->db->or_like('id_prospek', $q);
	$this->db->or_like('id_customer', $q);
	$this->db->or_like('nama_konsumen', $q);
	$this->db->or_like('nominal', $q);
	$this->db->or_like('tanggal_pembayaran', $q);
	$this->db->or_like('keterangan', $q);
    $this->db->or_like('status', $q);
    $this->db->where('id_prospek',$id_prospek);
    $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data2($limit, $start = 0, $q = NULL,$id_prospek) {
        $this->db->order_by($this->id, $this->order);
    $this->db->where('id_prospek',$id_prospek);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tagihan_konsumen_model.php */
/* Location: ./application/models/Tagihan_konsumen_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-05 16:46:39 */
/* http://harviacode.com */